# Generated by Django 4.1.1 on 2022-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_age', models.IntegerField()),
                ('employee_gender', models.CharField(max_length=100)),
                ('employee_phone', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_dept', models.CharField(max_length=100)),
                ('employee_desg', models.CharField(max_length=100)),
            ],
        ),
    ]
