# Generated by Django 4.1.1 on 2022-09-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='verification_doc',
            field=models.FileField(default='', upload_to='pdf'),
        ),
    ]
