# Generated by Django 4.1.1 on 2022-09-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_location', models.CharField(max_length=100)),
                ('dept_head', models.CharField(max_length=100)),
                ('dept_budget', models.CharField(max_length=100)),
                ('no_of_employees', models.IntegerField()),
            ],
        ),
    ]
